export const SAVE_EMPLOYEE_INFO1 = 'SAVE_EMPLOYEE_INFO1';

export const USER_CV_DETAILS_REQUEST = 'USER_CV_DETAILS_REQUEST';
export const USER_CV_DETAILS_SUCCESS = 'USER_CV_DETAILS_SUCCESS';
export const USER_CV_DETAILS_FAIL = 'USER_CV_DETAILS_FAIL';

export const USER_CV_UPDATE_REQUEST = 'USER_CV_UPDATE_REQUEST';
export const USER_CV_UPDATE_SUCCESS = 'USER_CV_UPDATE_SUCCESS';
export const USER_CV_UPDATE_FAIL = 'USER_CV_UPDATE_FAIL';
export const USER_CV_UPDATE_RESET = 'USER_CV_UPDATE_RESET';

export const APPROVE_CV_PROFILE_REQUEST = 'APPROVE_CV_PROFILE_REQUEST';
export const APPROVE_CV_PROFILE_SUCCESS = 'APPROVE_CV_PROFILE_SUCCESS';
export const APPROVE_CV_PROFILE_FAIL = 'APPROVE_CV_PROFILE_FAIL';
export const APPROVE_CV_PROFILE_RESET = 'APPROVE_CV_PROFILE_RESET';

export const CV_LIST_REQUEST = 'CV_LIST_REQUEST';
export const CV_LIST_SUCCESS= 'CV_LIST_SUCCESS';
export const CV_LIST_FAIL = 'CV_LIST_FAIL';

export const CV_DELETE_REQUEST = 'CV_DELETE_REQUEST';
export const CV_DELETE_SUCCESS = 'CV_DELETE_SUCCESS';
export const CV_DELETE_FAIL = 'CV_DELETE_FAIL';